---
- name: Build application profiles
  cisco.aci.aci_ap:
    ap: "{{ current_application.name }}"
    description: "{{ current_application.description }}"
    tenant: "{{ tenant_info.name }}"
    state: "{{ global_object_state }}"

- name: Create Endpoint Groups
  cisco.aci.aci_epg:
    tenant: "{{ tenant_info.name }}"
    bd: "{{ item.bridge_domain }}"
    ap: "{{ current_application.name }}"
    epg: "{{ item.name }}"
    description: "{{ item.description }}"
    state: "{{ global_object_state }}"
  loop: "{{ current_application.app_epg }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create EPG consumed contracts
  cisco.aci.aci_epg_to_contract:
    tenant: "{{ tenant_info.name }}"
    ap: "{{ current_application.name }}"
    contract: "{{ item.1 }}"
    epg: "{{ item.0.name }}"
    contract_type: consumer
    state: "{{ global_object_state }}"
  loop: "{{ current_application.app_epg | subelements('consumed_contracts', {'skip_missing': True}) }}"
  loop_control:
    label: "EPG: '{{ item.0.name }}' consuming contract '{{ item.1 }}'"

- name: Create EPG provided contracts
  cisco.aci.aci_epg_to_contract:
    tenant: "{{ tenant_info.name }}"
    ap: "{{ current_application.name }}"
    contract: "{{ item.1 }}"
    epg: "{{ item.0.name }}"
    contract_type: provider
    state: "{{ global_object_state }}"
  loop: "{{ current_application.app_epg | subelements('provided_contracts', {'skip_missing': True}) }}"
  loop_control:
    label: "EPG: '{{ item.0.name }}' providing contract '{{ item.1 }}'"
