stages:
    - build
    - test
    - deploy
image: alpine

compile_a:
stage: build
script:
    - echo "This job builds something quickly."
    
compile_b:
stage: build
script:
    - echo "This job builds something else slowly."

test_a:
stage: test
needs: [compile_a]
script:
    - echo "This test job will start as soon as compile_a finishes."
    - echo "It will not wait for compile_b, or other jobs in the build stage, to finish."

test_b:
stage: test
needs: [compile_b]
script:
    - echo "This test job will start as soon as compile_b finishes."
    - echo "It will not wait for other jobs in the build stage to finish."

deploy_a:
stage: deploy
needs: [test_a]
script:
    - echo "Since compile_a and test_a run quickly, this deploy job can run much earlier."
    - echo "It does not need to wait for compile_b or test_b."

deploy_b:
stage: deploy
needs: [test_b]
script:
    - echo "Since compile_b and test_b run slowly, this deploy job will run much later."