---
- hosts: localhost
  gather_facts: no
  vars:
    repositories:
      - { org: 'qsnyder', repo: 'arya' }
      - { org: 'qsnyder', repo: 'webarya' }
      - { org: 'datacenter', repo: 'acitoolkit' }
      - { org: 'CiscoDevNet', repo: 'pydme' }
    virtualenv: py3venv
    dev-folder: ~/bootcamp-aci
  
  tasks:
  - name: Create ACI code repository
    file:
      path: "{{ dev-folder }}"
      state: directory
      mode: '0755'

  - name: Clone code into directory
    git:
      repo: "https://github.com/{{ item.org }}/{{ item.repo }}.git"
      dest: "{{ dev_folder }}/{{ item.repo }}"
      with_items: "{{ repositories }}"

  - name: Install ACI toolkit, Arya
    shell: python setup.py install
    args:
      chdir: "{{ dev-folder }}/{{ item }}"
    with_items:
      - acitoolkit
      - arya
      - pydme

  - name: Install WebArya requirements
    pip: 
      requirements: "{{ dev-folder }}/webarya/requirements.txt"
      virtualenv: "{{ virtualenv }}"