stages:
    - pre_snapshot
    - test
    - post_snapshot


pre_snapshot_dev:
    stage: pre_snapshot
    image: python 
    script: 
        - git clone https://github.com/CiscoDevNet/ABC-ACI.git 
        - pip install 'pyats[full]' rest.connector
        - pip install genie.libs.sdk --upgrade --pre
        - cd ABC-ACI/pyats && pyats run job job.py --testbed-file aci_devnet_sandbox.yaml --trigger-datafile pre_trigger_datafile.yaml --html-logs pre_snapshots
    artifacts:
        when: always
        paths:
            - ABC-ACI/pyats/pre_snapshots/TaskLog.job.html
test_dev:
    stage: test
    image: python
    needs: [pre_snapshot_dev]
    script:
        - pip install ansible
        - ansible-galaxy collection install cisco.aci
        - python aci-automation.py

post_snapshot_dev:
    stage: post_snapshot
    image: python 
    needs: [test_dev]
    script: 
        - git clone https://github.com/CiscoDevNet/ABC-ACI.git 
        - pip install 'pyats[full]' rest.connector
        - pip install genie.libs.sdk --upgrade --pre
        - cd ABC-ACI/pyats && pyats run job job.py --testbed-file aci_devnet_sandbox.yaml --trigger-datafile post_trigger_datafile.yaml --html-logs post_snapshots
    artifacts:
        when: always
        paths:
            - ABC-ACI/pyats/post_snapshots/TaskLog.job.html
            