default:
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - pip install rest.connector==20.7
    


image: 'priel/devnet-nxos-bootcamp-runner:0.1.0'

stages:
  - pyats-pre-snapshot
  - deploy-ACI-config
  - pyats-post-snapshot
  
pyats-pre-snapshot:
  stage: pyats-pre-snapshot
  script: cd pyats && pyats run job job.py --testbed-file aci_devnet_sandbox.yaml --trigger-datafile pre_trigger_datafile.yaml --html-logs pre_snapshots
  artifacts:
      paths:
      - pyats/pre_snapshots/aepg.json
      - pyats/pre_snapshots/ap.json
      - pyats/pre_snapshots/bd.json
      - pyats/pre_snapshots/cp.json
      - pyats/pre_snapshots/ctx.json
      - pyats/pre_snapshots/filter.json
      - pyats/pre_snapshots/subnet.json
      - pyats/pre_snapshots/tenant.json
      when: always

deploy-ACI-config:
  stage: deploy-ACI-config
  script: 
    - ansible-galaxy collection install cisco.aci
    - ansible-playbook -i inventory aci-filter-entry.yml

pyats-post-snapshot:
  stage: pyats-post-snapshot
  script:
    - cd pyats && pyats run job job.py --testbed-file aci_devnet_sandbox.yaml --trigger-datafile post_trigger_datafile.yaml --html-logs post_snapshots
    - pyats diff pre_snapshots/aepg.json post_snapshots/aepg.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/ap.json post_snapshots/ap.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/bd.json post_snapshots/bd.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/cp.json post_snapshots/cp.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/ctx.json post_snapshots/ctx.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/filter.json post_snapshots/filter.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/subnet.json post_snapshots/subnet.json --output /builds/root/cicd/pyats/acidiff/
    - pyats diff pre_snapshots/tenant.json post_snapshots/tenant.json --output /builds/root/cicd/pyats/acidiff/
    - cat /builds/root/cicd/pyats/acidiff/diff_tenant.json 
    - cat /builds/root/cicd/pyats/acidiff/diff_filter.json

  artifacts:
      paths:
      - pyats/acidiff/diff_tenant.json 
      - pyats/acidiff/diff_filter.json

      when: always
