# Define filters and filter entries for contracts
---
filters:
  - name: app1
    tenant: common
    description: App server filter
  - name: web
    tenant: common
    description: Web server filter

filter_entries:
  - name: tcp_443
    target_filter: web
    description: HTTPS
    eth_type: ip
    ip_proto: tcp
    dest_port: https
  - name: tcp_80
    target_filter: web
    description: HTTP
    eth_type: ip
    ip_proto: tcp
    dest_port: 80
  - name: tcp_8443
    target_filter: app
    description: App server port
    eth_type: ip
    ip_proto: tcp
    dest_port: 80
  - name: udp_19703
    target_filter: app
    description: App server streaming data
    eth_type: ip
    ip_proto: udp
    dest_port: 19703

contracts:
  - name: phoenix_web
    app_profile: Phoenix
    tenant: "{{ tenant.name }}"
    description: Phoenix Web server contract
    subject: phoenix_dev_web
    filter: web
#    epg:
#      - name: web_servers
#        direction: provider
      #- name: app_servers
      #  direction: consumer
  - name: phoenix_app
    app_profile: Phoenix
    tenant: "{{ tenant.name }}"
    description: Phoenix App server contract
    subject: phoenix_dev_app
    filter: app
    epg:
      - name: app_servers
        direction: provider
      - name: web_servers
        direction: consumer
