---
- name: Create ACI Applications
  hosts: apic
  gather_facts: false
  environment:
    ACI_HOST: "{{ ansible_host }}"
    ACI_USERNAME: "{{ vault_ansible_user }}"
    ACI_PASSWORD: # <TODO> Use a variable to populate the APIC API password from the vault
    ACI_VALIDATE_CERTS: # <TODO> Use a variable to specify TLS validation behavior
  tasks:
    - name: Build application profiles
      cisco.aci.aci_ap:
        ap: "{{ item.name }}"
        description: # <TODO> Use a loop variable for the app profile description
        tenant: "{{ tenant_info.name }}"
        state: "{{ global_object_state }}"
      loop: "{{ tenant_info.applications }}"

    # Loop over the list of App Profiles and nested EPG definitions
    - name: Create Endpoint Groups
      cisco.aci.aci_epg:
        tenant: "{{ tenant_info.name }}"
        bd: "{{ tenant_info.bd_name }}"
        ap: "{{ item.0.name }}"
        epg: "{{ item.1.name }}"
        description: # <TODO> Use a subelement loop variable for the EPG description
        state: "{{ global_object_state }}"
      loop: "{{ tenant_info.applications | subelements('app_epg') }}"
