// Added a comment
// Some test


pipeline{
    agent {
        dockerfile {
            dir .
            filename 'Dockerfile'
            args '-u root --add-host apic:10.10.20.14 -v $HOME/.m2:/root/.m2 --entrypoint='
            // label 'pyats-ansible'
        }
    }
    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }
//              updateGitlabCommitStatus name: 'build', state: 'pending'
//              updateGitlabCommitStatus name: 'build', state: 'success'
        stage('Build in docker') {
             // agent { dockerfile true }
                // docker {
                    //image 'ciscotestautomation/pyats:latest-full'
                    // args "-u root -v $HOME/.m2:/root/.m2 --entrypoint=''"
                    // args "-u root -e WORKSPACE=/pyats -v ${env.WORKSPACE}/requirements.txt:/pyats/requirements.txt --entrypoint=''"
                    // args "-u root -v ${env.WORKSPACE}/requirements.txt:/pyats/requirements.txt"
                // }
            // }
            steps {
                updateGitlabCommitStatus name: 'build', state: 'pending'
                sh 'which pyats'
                sh 'which ansible-playbook'
                sh 'which pip'
                sh '/pyats/bin/pip install -r requirements.txt'
                sh 'pyats version check'
            }
        }
        stage('Pre snapshot') {
            steps {
                sh 'cd pyats ; pyats run job pre_change_job.py --testbed-file testbed.yaml --html-logs pre_snapshots'
            }
        }
        stage('Post snapshot') {
            steps {
                sh 'cd pyats ; pyats run job post_change_job.py --testbed-file testbed.yaml --html-logs post_snapshots'
            }
        }
//         stage('test code'){
//             steps{
//                 sh 'python content-pipelines-cje-labs/lab3_lab4/dog_pics_downloader/dog_pic_get_class.py'
//             }
//         }
    }
    post{
        always{
            echo "Job execution complete."
        }
        success{
            updateGitlabCommitStatus name: 'build', state: 'success'
            archiveArtifacts artifacts : 'pyats/pre_snapshots/*', 'pyats/post_snapshots/*'
            // archiveArtifacts artifacts : 'pyats/post_snapshots/*'
            // archiveArtifacts artifacts : '*.jpg'
        }
        unsuccessful{
            updateGitlabCommitStatus name: 'build', state: 'failed'
            echo "Job execution status is failed, please check error logs"
        }
//         cleanup{
//                 echo 'Cleaning up environment'
//                 sh 'rm -rf content-pipelines-cje-labs'
//         }
    }
}

// node() {
//     stage('Checkout') { checkout <your-scm-config> }
//
//     gitlabBuilds(builds: ["build", "test"]) {
//         stage("build") {
//           gitlabCommitStatus("build") {
//               // your build steps
//           }
//         }
//
//         stage("test") {
//           gitlabCommitStatus("test") {
//               // your test steps
//           }
//         }
//     }
// }
//