---
tenant_info:
  name:  # <TODO> Set tenant name
  vrfs:
    - name:  # <TODO> Set VRF Name
  bridge_domains:
    - name: Birch_Private_Servers
      vrf: Server_VRF
      subnets:
        - ip: 192.168.16.1/24
    - name:  # <TODO> Create Public Server BD
      vrf:  # <TODO> Set VRF for Public Server BD
      subnets:
        - ip: # <TODO> Create subnet for Public Server BD

  applications:
    - name: Birch_App
      description: Project Birch Application Profile
      app_epg:
        - name: Birch_Web_Servers
          description: Project Birch Web Servers
          bridge_domain: Birch_Public_Servers
          consumed_contracts:
            - Birch_App_Services
          provided_contracts:
            -  # <TODO> Set provided contract for Web Servers
        - name: Birch_App_Servers
          description: Project Birch App Servers
          bridge_domain:  # <TODO> Set bridge domain for App Servers
          provided_contracts:
            - # <TODO> Set provided contract for App Servers

  contract_filters:
    - name: Birch_App
      description: Project Birch application services
      filter_entries:
        - name: tcp_8443
          description: App server port
          eth_type: ip
          ip_proto: tcp
          dest_port: 80
        - name: udp_19703
          description: App server streaming data
          eth_type: ip
          ip_proto: udp
          dest_port: 19703
    - name: Birch_Web
      description: Project Birch web services
      filter_entries:
        - name: tcp_443
          description: HTTPS
          eth_type: ip
          ip_proto: tcp
          dest_port: https
        - name: tcp_80
          description: HTTP
          eth_type: ip
          ip_proto: tcp
          dest_port: 80

  contracts:
    - name: Birch_Web_Services
      description: Project Birch Web server contract
      subjects:
        - subject: Birch_Web
          filters:
            - Birch_Web
    - name: Birch_App_Services
      description: Project Birch App server contract
      subjects:
        - subject: Birch_App
          filters:
            - Birch_App
