---
#############################
#  Playbook for ACI TENANTS #
#############################

- name: ACI Tenant Management
  hosts: 
    - apic
  gather_facts: false
  connection: local

  tasks:
  - name: Test for ACI hostname, apic_username, and apic_password. Setup Login Anchor and Alias
    fail:
      msg: 'Please define the variables: apic_username and apic_password.'
    when: apic_username is not defined or apic_password is not defined
    vars:
      login_info: &login_info
        hostname: "{{ inventory_hostname }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"

  - name: CONFIGURE TENANT
    aci_tenant:
      <<: *login_info
      tenant: "{{ tenant }}"
      description: "Tenant Created/Configured Using Ansible"
      state: "{{ aci_state }}"
      validate_certs: "{{ validate_certs }}"
    when: aci_state == 'present'

  - name: TENANT TASKS
    include_tasks:
      file: aci-tenant_tasks.yaml
    when: aci_state == 'present'

  - name: DELETE TENANT
    aci_tenant:
      <<: *login_info
      tenant: "{{ tenant }}"
      state: "{{ aci_state }}"
      validate_certs: "{{ validate_certs }}"
    when: aci_state == 'absent'
