---
- name: Create a tenant using Ansible
  hosts: apic
  gather_facts: false
  tasks:
    - name: Create Tenant
      cisco.aci.aci_tenant:
        tenant: "{{ tenant_info.name }}"
        state: "{{ global_object_state }}"  # <TODO> Use a variable to set the tenant state
        host: "{{ ansible_host }}"
        username: "{{ vault_ansible_user }}"
        password: "{{ vault_ansible_password }}"
        validate_certs: false

    - name: Create VRF
      cisco.aci.aci_vrf:
        tenant: "{{ tenant_info.name }}"
        vrf: "{{ tenant_info.vrf_name }}"  # <TODO> Use a variable to set the VRF name
        state: "{{ global_object_state }}"
        host: "{{ ansible_host }}"
        username: "{{ vault_ansible_user }}"
        password: "{{ vault_ansible_password }}"
        validate_certs: false

    - name: Create Bridge Domain
      cisco.aci.aci_bd:
        tenant: "{{ tenant_info.name }}"
        vrf: "{{ tenant_info.vrf_name }}"
        bd: "{{ tenant_info.bd_name }}"
        state: "{{ global_object_state }}"
        host: "{{ ansible_host }}"
        username: "{{ vault_ansible_user }}"
        password: "{{ vault_ansible_password }}"
        validate_certs: false

    - name: Create subnets
      cisco.aci.aci_bd_subnet:
        tenant: "{{ tenant_info.name }}"
        bd: "{{ tenant_info.bd_name }}"
        gateway: "{{ item | ansible.netcommon.ipaddr('ip') }}"
        mask: "{{ item | ansible.netcommon.ipaddr('prefix') }}"
        state: "{{ global_object_state }}"
        host: "{{ ansible_host }}"
        username: "{{ vault_ansible_user }}"
        password: "{{ vault_ansible_password }}"
        validate_certs: false
      loop: "{{ tenant_info.subnets }}"
