---
- name: Create ACI Tenant
  hosts: apic
  gather_facts: false
  environment:
    # <TODO> Set environment variables for APIC connectivity
  tasks:
    - name: Create contract filters
      include_tasks:  # <TODO> Include the correct task file
      loop: "{{ tenant_info.contract_filters }}"
      loop_control:
        loop_var:  # <TODO> Set the name of the loop variable

    - name: Create contracts
      include_tasks:  # <TODO> Include the correct task file
      loop:  # <TODO> Loop over tenant contracts
      loop_control:
        loop_var:  # <TODO> Set the name of the loop variable
