---
- name: Create ACI Tenant
  hosts: apic
  gather_facts: false
  environment:
    ACI_HOST: "{{ ansible_host }}"
    ACI_USERNAME: "{{ vault_ansible_user }}"
    ACI_PASSWORD: "{{ vault_ansible_password }}"
    ACI_VALIDATE_CERTS: false
  tasks:
    - name: Create contract filters
      include_tasks: # <TODO> Specify the task file to include from the task_files directory
      loop: # <TODO> Specify the list to iterate
      loop_control:
        loop_var: # <TODO> Specify the name of the loop variable to be created instead of "item"

    - name: Create contracts
      include_tasks: # <TODO> Specify the task file to include from the task_files directory
      loop: "{{ tenant_info.contract_info.contracts }}"
      loop_control:
        # <TODO> Specify the name of the loop variable to be created instead of "item"
