---
- name: Configure ACI with Ansible
  hosts: apic
  gather_facts: false
  environment:
    ACI_HOST: "{{ ansible_host }}"
    ACI_USERNAME: "{{ ansible_user }}"
    ACI_PASSWORD: "{{ ansible_password }}"
    ACI_VALIDATE_CERTS: false
  tasks:
    - name: "Create tenant '{{ tenant.name }}'"
      cisco.aci.aci_tenant:
        tenant: "{{ tenant.name }}"
        description: "{{ tenant.description }}"
        state: present
      register: new_tenant

    - name: Show the contents of the new_tenant variable
      ansible.builtin.debug:
        msg: "{{ new_tenant }}"
      when:
        - debug_enabled

    - name: Set a new global variable to store the tenant name
      ansible.builtin.set_fact:
        new_tenant_name: "{{ new_tenant.mo.fvTenant.attributes.name }}"

    - name: "Create Bridge Domain '{{ bridge_domain.name }}'"
      cisco.aci.aci_bd:
        bd: "{{ bridge_domain.name }}"
        description: "{{ bridge_domain.description }}"
        tenant: "{{ new_tenant_name }}"
      register: new_bd

    # Override the host debug variable with a task variable
    - name: Show the contents of the new_tenant variable
      ansible.builtin.debug:
        msg: "{{ new_bd }}"
      when:
        - debug_enabled
      vars:
        debug_enabled: false

    - name: "Create VRF '{{ vrf.name }}'"
      cisco.aci.aci_vrf:
        tenant: "{{ new_tenant_name }}"
        vrf: "{{ vrf.name }}"
        description: "{{ vrf.description }}"

    # Use task variables to set the Bridge domain name and define subnets
    - name: "Create subnets in BD '{{ bridge_domain.name }}'"
      cisco.aci.aci_bd_subnet:
        tenant: "{{ new_tenant_name }}"
        bd: "{{ bd_name }}"
        gateway: "{{ network_gateway }}"
        mask: "{{ network_mask }}"
        description: "{{ item.description }}"
      loop: "{{ subnets }}"
      vars:
        bd_name: "{{ new_bd.mo.fvBD.attributes.name }}"
        network_gateway: "{{ item.ip_network | ansible.netcommon.ipaddr('address') }}"
        network_mask: "{{ item.ip_network | ansible.netcommon.ipaddr('prefix') }}"
        subnets:
          - ip_network: 172.22.8.1/24
            description: Phoenix web servers
          - ip_network: 172.22.16.1/24
            description: Phoenix app servers

    - name: Store the Bridge Domain name as a fact to reduce repetition
      ansible.builtin.set_fact:
        new_bd_name: "{{ new_bd.mo.fvBD.attributes.name }}"

    - name: Build application profiles
      cisco.aci.aci_ap:
        ap: "{{ item.name }}"
        description: "{{ item.description }}"
        tenant: "{{ new_tenant_name }}"
      loop: "{{ applications }}"

    # Loop over the list of App Profiles and nested EPG definitions
    - name: Create Endpoint Groups
      cisco.aci.aci_epg:
        tenant: "{{ new_tenant_name }}"
        bd: "{{ new_bd_name }}"
        ap: "{{ item.0.name }}"
        epg: "{{ item.1.name }}"
        description: "{{ item.1.description }}"
      loop: "{{ applications | subelements('app_epg') }}"

    - name: Include tasks to create contracts
      ansible.builtin.include_tasks: build_contracts.yml
