default:
  image: 'priel/devnet-nxos-bootcamp-runner:0.1.0'
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False


stages:
  - pyats-pre-snapshot
  - deploy-ACI
  - pyats-post-snapshot
  
pyats-pre-snapshot:
  stage: pyats-pre-snapshot
  script: 
    - pip install 'pyats[full]' rest.connector
    - cd pyats && pyats run job job.py --testbed-file aci_devnet_sandbox.yaml --trigger-datafile pre_trigger_datafile.yaml --html-logs pre_snapshots
  artifacts:
      paths:
      - pyats/pre_snapshots/TaskLog.job.html
      when: always

deploy-ACI:
  stage: deploy-ACI
  script: ansible-playbook -i hosts.yaml create_tenants.yml

pyats-post-snapshot:
  stage: pyats-post-snapshot
  script: 
    - pip install 'pyats[full]' rest.connector
    - cd pyats && pyats run job job.py --testbed-file aci_devnet_sandbox.yaml --trigger-datafile post_trigger_datafile.yaml --html-logs post_snapshots
    - pyats diff post_snapshots/tenant.json pre_snapshots/tenant.json --output acidiff/
    - pyats diff post_snapshots/ctx.json pre_snapshots/ctx.json --output acidiff/
    - cat acidiff/diff_tenant.json
    - cat acidiff/diff_ctx.json
    

  artifacts:
      paths:
      - pyats/post_snapshots/TaskLog.job.html
      when: always
